"""First-run setup window: pick a provider, enter the API key / model,
test the connection, and save to .env."""
import base64
import os
import sys
import tkinter as tk
from pathlib import Path
from tkinter import messagebox, ttk

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"

TINY_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
)

PROVIDER_META = {
    "doubao": ("ARK_API_KEY", "ARK_MODEL_ID", "火山方舟推理接入点 ID（如 ep-xxxx），默认模型名常不可用"),
    "openai": ("OPENAI_API_KEY", "OPENAI_MODEL", "模型名，默认 gpt-4o-mini"),
    "qwen": ("DASHSCOPE_API_KEY", "QWEN_MODEL", "模型名，默认 qwen-vl-plus"),
    "zhipu": ("ZHIPU_API_KEY", "ZHIPU_MODEL", "模型名，默认 glm-4v-plus"),
    "custom": ("VISION_API_KEY", "VISION_MODEL", "需同时设置 VISION_BASE_URL"),
}


def _read_env():
    values = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8-sig").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            values[k.strip()] = v.strip().strip('"').strip("'")
    return values


def _save_env(entries):
    lines = [
        "# Generated by doubao-multimodal setup window.",
        "# Fill in the keys you use; unset lines are ignored.",
        "",
    ]
    for k, v in entries.items():
        if v:
            lines.append(f"{k}={v}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    for k, v in entries.items():
        if v:
            os.environ[k] = v


def run(initial_provider=None):
    sys.path.insert(0, str(ROOT))
    import env_loader
    from providers.vision import recognize

    env_loader.load_env_file()
    existing = _read_env()

    root = tk.Tk()
    root.title("配置 API Key - doubao-multimodal")
    root.geometry("620x430")
    root.configure(bg="#F4F6F9")

    tk.Label(root, text="首次使用，请配置视觉模型 API", bg="#F4F6F9",
             font=("Microsoft YaHei UI", 13, "bold")).pack(anchor="w", padx=20, pady=(14, 4))
    tk.Label(root, text="选择厂商并填入 Key；可先点\"测试连接\"验证。", bg="#F4F6F9",
             fg="#6B7280", font=("Microsoft YaHei UI", 9)).pack(anchor="w", padx=20)

    form = tk.Frame(root, bg="#F4F6F9")
    form.pack(fill="x", padx=20, pady=(12, 4))
    form.columnconfigure(1, weight=1)

    providers = list(PROVIDER_META)
    tk.Label(form, text="厂商", bg="#F4F6F9", font=("Microsoft YaHei UI", 10)).grid(row=0, column=0, sticky="w", pady=6)
    provider_var = tk.StringVar(value=initial_provider if initial_provider in providers else "doubao")
    combo = ttk.Combobox(form, textvariable=provider_var, values=providers, state="readonly", width=30)
    combo.grid(row=0, column=1, sticky="we", pady=6)

    def meta():
        return PROVIDER_META[provider_var.get()]

    tk.Label(form, text="API Key", bg="#F4F6F9", font=("Microsoft YaHei UI", 10)).grid(row=1, column=0, sticky="w", pady=6)
    key_var = tk.StringVar(value=existing.get(meta()[0], ""))
    key_entry = tk.Entry(form, textvariable=key_var, show="*", width=40)
    key_entry.grid(row=1, column=1, sticky="we", pady=6)

    tk.Label(form, text="模型 / 接入点 ID", bg="#F4F6F9", font=("Microsoft YaHei UI", 10)).grid(row=2, column=0, sticky="w", pady=6)
    model_var = tk.StringVar(value=existing.get(meta()[1], ""))
    model_entry = tk.Entry(form, textvariable=model_var, width=40)
    model_entry.grid(row=2, column=1, sticky="we", pady=6)
    hint = tk.Label(form, text="", bg="#F4F6F9", fg="#6B7280",
                    font=("Microsoft YaHei UI", 8), wraplength=420, justify="left")
    hint.grid(row=3, column=1, sticky="w")
    hint.configure(text=meta()[2])

    def on_provider_change(_event=None):
        key_var.set(existing.get(meta()[0], ""))
        model_var.set(existing.get(meta()[1], ""))
        hint.configure(text=meta()[2])

    combo.bind("<<ComboboxSelected>>", on_provider_change)

    status = tk.Label(root, text="", bg="#F4F6F9", fg="#D97706",
                      font=("Microsoft YaHei UI", 9), wraplength=560, justify="left")
    status.pack(anchor="w", padx=20, pady=(6, 2))

    def test_connection():
        provider = provider_var.get()
        key = key_var.get().strip()
        model = model_var.get().strip() or None
        status.configure(text="测试中…", fg="#D97706")
        root.update()
        if not key:
            status.configure(text="请先填写 API Key", fg="#DC2626")
            return
        _save_env({meta()[0]: key, meta()[1]: model or ""})
        try:
            answer, usage, cfg = recognize(
                "data:image/png;base64," + base64.b64encode(TINY_PNG).decode(),
                "ok", provider=provider, model=model, timeout=40)
            status.configure(text=f"连接成功 ✔  模型: {cfg['model']}  "
                                  f"token: {usage.get('total_tokens', 0)}", fg="#16A34A")
        except Exception as exc:
            msg = str(exc)
            if "InvalidEndpointOrModel" in msg:
                msg += "  ← 请把模型栏填成方舟推理接入点 ID（ep-xxxx）"
            elif "401" in msg or "Unauthorized" in msg:
                msg += "  ← API Key 无效，请检查"
            status.configure(text="连接失败: " + msg[:300], fg="#DC2626")

    def save_and_exit():
        provider = provider_var.get()
        key = key_var.get().strip()
        model = model_var.get().strip()
        if not key:
            status.configure(text="请先填写 API Key 再保存", fg="#DC2626")
            return
        _save_env({meta()[0]: key, meta()[1]: model})
        os.environ["VISION_PROVIDER"] = provider
        root.destroy()
        return True

    btns = tk.Frame(root, bg="#F4F6F9")
    btns.pack(fill="x", padx=20, pady=(10, 14))
    ttk.Button(btns, text="测试连接", command=test_connection).pack(side="left")
    ttk.Button(btns, text="保存并继续", command=save_and_exit).pack(side="right")

    root.mainloop()
    return True


if __name__ == "__main__":
    run()
